name: PullRequest

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - run: dotnet tool restore
    - run: dotnet sln ./src/NonCopyable.sln remove ./src/NonCopyable/NonCopyable.Vsix/NonCopyable.Vsix.csproj
    - run: dotnet restore ./src/NonCopyable.sln
    - run: dotnet build ./src/NonCopyable.sln --no-restore
    - run: dotnet test ./src/NonCopyable.sln --no-build -l:xunit
    - run: dotnet dotnet-xunit-to-junit ./src/NonCopyable/NonCopyable.Test/TestResults/TestResults.xml TestResults.xml
      if: always()
    - uses: test-summary/action@v2
      with:
        paths: "TestResults.xml"
      if: always()
